### ISSUE TITLE
wrong type in input parameter `--max-iou-dist`

### ISSUE THREAD

**Issue by BarRozenman** [sithu31296/simple-object-tracking#2]
a small mistake, the parameter type is set to int even though its clearly a float.
I suggest changing 
   ` parser.add_argument('--max-iou-dist', type=int, default=0.7)`
to
   ` parser.add_argument('--max-iou-dist', type=float, default=0.7)`

https://github.com/sithu31296/simple-object-tracking/blob/4e86e53e78799c5cb92d2f1cddd2df071530e98e/track.py#L104

**Comment by sithu31296** [comment]
Yes. It is a mistake. Thanks for reminding.
